---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-installing-pcp"
      label: "Installing Pcp"
      solveButton: false
    - name: "02-pcp-system-metrics"
      label: "Pcp System Metrics"
      solveButton: false
    - name: "03-pcp-web-console"
      label: "Pcp Web Console"
      solveButton: false
    - name: "04-troubleshooting-cpu"
      label: "Troubleshooting Cpu"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty_rhel/ssh/root
  - name: "RHEL Webconsole"
    url: https://cockpit-${guid}.${domain}/
